[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl_1_1"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run railway:prepare",
  "npm run build",
  "npx prisma generate"
]

[start]
cmd = "npm run start"

